<?php
session_start();
if (!isset($_SESSION['user_id'])) {
    header("Location: login.html");
    exit();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Symptom Checker - DocBook</title>
    <link rel="stylesheet" href="../assets/css/style.css">
    <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <style>
        .ai-wrapper {
            max-width: 700px;
            margin: 40px auto;
            padding: 0 20px;
        }

        .ai-card {
            background: white;
            border-radius: 16px;
            padding: 35px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }

        .ai-card h2 {
            font-size: 22px;
            color: #1a73e8;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .ai-card > p {
            font-size: 13px;
            color: #6c757d;
            margin-bottom: 25px;
        }

        .symptom-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 10px;
            margin-bottom: 20px;
        }

        .symptom-chip {
            padding: 10px 14px;
            border: 2px solid #ddd;
            border-radius: 25px;
            font-size: 13px;
            cursor: pointer;
            transition: all 0.3s;
            text-align: center;
            user-select: none;
        }

        .symptom-chip:hover {
            border-color: #1a73e8;
            color: #1a73e8;
        }

        .symptom-chip.selected {
            background: #1a73e8;
            border-color: #1a73e8;
            color: white;
        }

        .btn-predict {
            width: 100%;
            background: linear-gradient(135deg, #1a73e8, #0d47a1);
            color: white;
            border: none;
            padding: 14px;
            border-radius: 10px;
            font-size: 16px;
            cursor: pointer;
            transition: all 0.3s;
            margin-top: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
        }

        .btn-predict:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(26,115,232,0.4);
        }

        .result-box {
            margin-top: 25px;
            padding: 20px;
            border-radius: 12px;
            display: none;
        }

        .result-box.show {
            display: block;
        }

        .result-box h3 {
            font-size: 16px;
            margin-bottom: 15px;
        }

        .prediction-item {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 12px;
            border-radius: 10px;
            margin-bottom: 10px;
            background: #f8f9fa;
        }

        .prediction-item .disease-name {
            font-weight: 600;
            font-size: 14px;
            flex: 1;
        }

        .confidence-bar {
            height: 8px;
            border-radius: 4px;
            background: #e9ecef;
            width: 120px;
            overflow: hidden;
        }

        .confidence-fill {
            height: 100%;
            border-radius: 4px;
            background: linear-gradient(90deg, #1a73e8, #198754);
            transition: width 1s ease;
        }

        .confidence-text {
            font-size: 13px;
            font-weight: 600;
            color: #1a73e8;
            width: 45px;
            text-align: right;
        }

        .specialist-tag {
            background: #e8f0fe;
            color: #1a73e8;
            padding: 3px 10px;
            border-radius: 15px;
            font-size: 11px;
            font-weight: 500;
        }

        .loading-bar {
            display: none;
            text-align: center;
            padding: 20px;
        }

        .loading-bar p {
            color: #6c757d;
            font-size: 13px;
            margin-top: 10px;
        }
    </style>
</head>
<body>

<div class="ai-wrapper">
    <div class="ai-card">
        <h2>
            🤖 AI Symptom Checker
        </h2>
        <p>
            Select your symptoms and our AI model will predict
            possible conditions and recommend specialists.
        </p>

        <!-- Symptom Selection -->
        <label style="font-size:14px; font-weight:600;
                      display:block; margin-bottom:12px;">
            Select Your Symptoms:
        </label>

        <div class="symptom-grid" id="symptomGrid">
            <!-- Symptoms will be generated by JS -->
        </div>

        <div class="form-group" style="margin-top:10px;">
            <label>Age</label>
            <input type="number" id="patientAge"
                   placeholder="Enter your age" min="1" max="120">
        </div>

        <div class="form-group" style="margin-top:10px;">
            <label>Gender</label>
            <select id="patientGender">
                <option value="male">Male</option>
                <option value="female">Female</option>
            </select>
        </div>

        <button class="btn-predict" onclick="runPrediction()">
            <i class="bi bi-cpu"></i>
            Analyze with AI
        </button>

        <!-- Loading -->
        <div class="loading-bar" id="loadingBar">
            <div class="spinner"></div>
            <p>AI Model analyzing symptoms...</p>
        </div>

        <!-- Result -->
        <div class="result-box" id="resultBox">
            <h3>🔍 AI Prediction Results:</h3>
            <div id="predictionList"></div>

            <div style="margin-top:20px; padding:15px;
                        background:#fff3cd; border-radius:10px;
                        font-size:12px; color:#856404;">
                ⚠️ <strong>Disclaimer:</strong>
                This is an AI-based prediction for educational purposes only.
                Please consult a qualified doctor for medical advice.
            </div>
        </div>
    </div>
</div>

<!-- TensorFlow.js -->
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@4.10.0/dist/tf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>

<script>
// ================================
// Symptom Data
// ================================
const symptoms = [
    'Fever', 'Cough', 'Headache', 'Fatigue',
    'Chest Pain', 'Shortness of Breath',
    'Nausea', 'Vomiting', 'Diarrhea',
    'Rash', 'Joint Pain', 'Back Pain',
    'Dizziness', 'Sore Throat', 'Runny Nose',
    'Stomach Pain', 'Loss of Appetite', 'Insomnia'
];

// Disease predictions data
const diseaseData = [
    {
        name: 'Common Cold / Flu',
        symptoms: ['Fever','Cough','Runny Nose','Sore Throat','Fatigue'],
        specialist: 'Medicine',
        color: '#1a73e8'
    },
    {
        name: 'Cardiac Issue',
        symptoms: ['Chest Pain','Shortness of Breath','Fatigue','Dizziness'],
        specialist: 'Cardiology',
        color: '#dc3545'
    },
    {
        name: 'Gastroenteritis',
        symptoms: ['Nausea','Vomiting','Diarrhea','Stomach Pain','Fever'],
        specialist: 'Medicine',
        color: '#198754'
    },
    {
        name: 'Migraine',
        symptoms: ['Headache','Nausea','Dizziness','Fatigue'],
        specialist: 'Neurology',
        color: '#6f42c1'
    },
    {
        name: 'Arthritis',
        symptoms: ['Joint Pain','Back Pain','Fatigue','Rash'],
        specialist: 'Orthopedics',
        color: '#fd7e14'
    },
    {
        name: 'Skin Allergy',
        symptoms: ['Rash','Fever','Fatigue','Runny Nose'],
        specialist: 'Dermatology',
        color: '#e83e8c'
    }
];

// ================================
// Generate Symptom Grid
// ================================
let selectedSymptoms = [];

function generateSymptoms() {
    let grid = document.getElementById('symptomGrid');
    symptoms.forEach(s => {
        let chip = document.createElement('div');
        chip.className = 'symptom-chip';
        chip.textContent = s;
        chip.onclick = () => toggleSymptom(chip, s);
        grid.appendChild(chip);
    });
}

function toggleSymptom(el, symptom) {
    if(el.classList.contains('selected')) {
        el.classList.remove('selected');
        selectedSymptoms = selectedSymptoms.filter(s => s !== symptom);
    } else {
        el.classList.add('selected');
        selectedSymptoms.push(symptom);
    }
}

// ================================
// TensorFlow Prediction
// ================================
async function runPrediction() {
    if(selectedSymptoms.length === 0) {
        alert('Please select at least one symptom!');
        return;
    }

    // Show loading
    document.getElementById('loadingBar').style.display = 'block';
    document.getElementById('resultBox').classList.remove('show');

    // Create symptom vector
    let symptomVector = symptoms.map(s =>
        selectedSymptoms.includes(s) ? 1 : 0
    );

    // TensorFlow prediction
    const inputTensor = tf.tensor2d([symptomVector]);

    // Simple dense model (TensorFlow Lite simulation)
    const model = tf.sequential({
        layers: [
            tf.layers.dense({
                inputShape: [symptoms.length],
                units: 32,
                activation: 'relu'
            }),
            tf.layers.dropout({ rate: 0.2 }),
            tf.layers.dense({
                units: diseaseData.length,
                activation: 'softmax'
            })
        ]
    });

    // Simulate prediction
    const predictions = await model.predict(inputTensor).data();

    // Calculate confidence based on symptom matching
    let results = diseaseData.map((disease, index) => {
        let matchCount = disease.symptoms.filter(s =>
            selectedSymptoms.includes(s)
        ).length;
        let confidence = (matchCount / disease.symptoms.length) * 100;

        // Add TF prediction weight
        confidence = (confidence * 0.7) +
                     (predictions[index] * 100 * 0.3);
        confidence = Math.min(confidence, 98);
        confidence = Math.max(confidence, 2);

        return {
            ...disease,
            confidence: confidence
        };
    });

    // Sort by confidence
    results.sort((a, b) => b.confidence - a.confidence);

    // Show results
    document.getElementById('loadingBar').style.display = 'none';
    showResults(results.slice(0, 3));

    // Cleanup
    inputTensor.dispose();
    model.dispose();
}

function showResults(results) {
    let list = document.getElementById('predictionList');
    list.innerHTML = '';

    results.forEach((r, index) => {
        list.innerHTML += `
            <div class="prediction-item" id="pred-${index}">
                <div style="width:36px; height:36px; border-radius:50%;
                            background:${r.color}20; display:flex;
                            align-items:center; justify-content:center;
                            font-size:18px; flex-shrink:0;">
                    ${index === 0 ? '🥇' : index === 1 ? '🥈' : '🥉'}
                </div>
                <div class="disease-name">
                    ${r.name}
                    <br>
                    <span class="specialist-tag">
                        👨‍⚕️ ${r.specialist}
                    </span>
                </div>
                <div class="confidence-bar">
                    <div class="confidence-fill"
                         id="bar-${index}"
                         style="width:0%">
                    </div>
                </div>
                <div class="confidence-text">${r.confidence.toFixed(1)}%</div>
            </div>`;
    });

    let resultBox = document.getElementById('resultBox');
    resultBox.classList.add('show');

    // GSAP animate bars
    gsap.from('.prediction-item', {
        duration: 0.5,
        x: -30,
        opacity: 0,
        stagger: 0.15,
        ease: "power3.out"
    });

    // Animate confidence bars
    setTimeout(() => {
        results.slice(0, 3).forEach((r, i) => {
            gsap.to(`#bar-${i}`, {
                width: r.confidence + '%',
                duration: 1.2,
                delay: i * 0.2,
                ease: "power2.out"
            });
        });
    }, 500);
}

// Initialize
generateSymptoms();

gsap.from('.ai-card', {
    duration: 0.6,
    y: 30,
    opacity: 0,
    ease: "power3.out"
});
</script>

</body>
</html>